import { capabilities, projects, regions, additionalApprovals } from './data.js';

const heading=(label:string,title:string)=>`<div class="section-heading reveal"><p class="eyebrow">${label}</p><h2>${title}</h2></div>`;
const linePatterns = ['M12 62V24L38 10V62M38 62V32L65 18V62M6 62H74M20 35H29M20 44H29M46 42H56M46 51H56','M8 61H72M18 61V25H62V61M8 25L40 8L72 25M29 61V40H51V61','M10 67L30 12M70 67L50 12M40 62V52M40 42V32M40 22V12','M10 65V12H70V65M10 12L70 65M70 12L10 65M10 38H70','M12 26L40 10L68 26M18 30V59M33 30V59M48 30V59M63 30V59M10 64H70','M9 63V35L29 24V35L49 24V35L70 24V63ZM59 29V10H68V25M19 46V53M34 46V53M49 46V53'];
export function renderSections(){
 const p=projects[0];
 return `
 <section class="section capabilities" id="capabilities"><div class="split-heading">${heading('02 / OUR CAPABILITIES','Built across<br><span>disciplines.</span>')}<p class="section-intro">From the first structural decision to the finishing detail, a connected approach to the built environment.</p></div><div class="capability-grid">${capabilities.map(([title,desc],i)=>`<article class="capability-card reveal"><div class="card-top"><span>0${i+1}</span><svg viewBox="0 0 80 80" fill="none" aria-hidden="true"><path d="${linePatterns[i]}"/></svg></div><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div></section>
 <section class="showcase" id="project-showcase" aria-labelledby="showcase-heading"><div class="showcase-heading"><div><p class="eyebrow light">03 / PROJECT CAPABILITIES</p><h2 id="showcase-heading">Engineering across<br><em>every scale.</em></h2></div><p>Built environments.<br>Engineered with purpose.<span class="showcase-disclaimer">Representative presentation visuals.<br>Not a portfolio of verified completed projects.</span></p></div>
 <div class="carousel" role="region" aria-roledescription="carousel" aria-label="Representative project capabilities" tabindex="0"><div class="carousel-toolbar"><p>INFRASTRUCTURE VISION</p><div class="carousel-controls"><span class="slide-counter"><strong id="slide-counter">01</strong> / 07</span><button class="round-button" id="previous-slide" aria-label="Previous capability">←</button><button class="round-button" id="next-slide" aria-label="Next capability">→</button><button class="round-button pause-button" id="toggle-autoplay" aria-label="Pause slideshow" aria-pressed="false">Ⅱ</button></div></div>
 <div class="slide-stage" id="slide-stage"><img class="slide-image active" src="./assets/${p.key}.webp" width="1672" height="941" loading="lazy" alt="${p.alt}"></div><p class="sr-only" id="slide-announcement" aria-live="polite" aria-atomic="true"></p>
 <div class="slide-information"><div><p class="eyebrow light" id="slide-eyebrow">${p.eyebrow}</p><h3 id="slide-title">${p.title}</h3><p id="slide-description">${p.description}</p></div><dl class="slide-specs"><div><dt>Category</dt><dd id="slide-category">${p.category}</dd></div><div><dt>Capability</dt><dd id="slide-capability">${p.capability}</dd></div><div><dt>Expertise</dt><dd id="slide-expertise">${p.expertise}</dd></div></dl></div>
 <div class="project-selector" role="group" aria-label="Choose a project capability">${projects.map((project,i)=>`<button data-slide="${i}" aria-label="Show ${project.label} capability, slide ${i+1} of 7" ${i===0?'aria-current="true"':''}><span>0${i+1}</span>${project.label}</button>`).join('')}</div></div></section>
 <section class="section why" id="approach"><div class="split-heading">${heading('04 / THE HANS BUILDERS APPROACH','A foundation<br>for <span>the long term.</span>')}<p class="section-intro">Engineering capability.<br>Regional execution.<br>Corporate accountability.</p></div><div class="why-grid">${[['Decades of foundation','Corporate roots dating to 1978. An enduring framework for the work ahead.'],['Engineering-led execution','Construction decisions grounded in engineering discipline and structural reliability.'],['Regional operating network','Coordination across key northern Indian infrastructure corridors.'],['Corporate accountability','Established corporate structure and an emphasis on project accountability.']].map(([title,desc],i)=>`<article class="reveal"><span class="index">0${i+1}</span><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div></section>
 <section class="compliance" id="compliance"><div class="section"><div class="split-heading">${heading('05 / CORPORATE CREDENTIALS','Built on compliance.<br><em>Engineered for accountability.</em>')}<p class="section-intro">Hans Builders Contractors<br>and Engineer Pvt. Ltd.<br><span class="credential-note">Incorporated 04 July 1978</span></p></div><dl class="credential-grid"><div><dt>Corporate Identity Number</dt><dd class="cin">U74899DL1978PTC009103</dd></div><div><dt>RoC / MCA Registration No.</dt><dd>009103</dd></div><div><dt>Registered office</dt><dd>IE/2, Jhandewalan Extension<br>New Delhi, Delhi 110055, India</dd></div><div><dt>Corporate status</dt><dd>Active<small>As recorded in the supplied company dossier</small></dd></div></dl>${additionalApprovals.filter(a=>a.verified).map(a=>`<article><h3>${a.name}</h3><p>${a.detail}</p></article>`).join('')}
 <div class="certifications"><div><p class="eyebrow light">CERTIFICATIONS & COMPLIANCE</p><h3>Standards that<br>frame our approach.</h3><p class="standards-note">Standards referenced on company letterhead.<br>Certificate details and validity are not provided.</p></div><div class="standards-list"><div><span>01</span><strong>ISO 9001:2015</strong><p>Quality management</p></div><div><span>02</span><strong>ISO 22000:2005</strong><p>Management standard</p></div><div><span>03</span><strong>ISO 14005:2020</strong><p>Environmental management framework</p></div></div></div></div></section>
 <section class="section footprint" id="footprint"><div class="split-heading">${heading('06 / REGIONAL FOOTPRINT','Engineering across<br><span>North India.</span>')}<p class="section-intro">A New Delhi base.<br>A connected regional perspective.</p></div><div class="footprint-layout"><div class="network-panel"><div class="network-heading"><span>REGIONAL NETWORK</span><span>INDIA / NORTH</span></div><div class="network-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${regions.slice(1).map(r=>`<path class="network-line" d="M49 59 Q${(r.x+49)/2+10} ${(r.y+59)/2} ${r.x} ${r.y}"/>`).join('')}</svg>${regions.map((r,i)=>`<button class="region-node ${i===0?'selected':''}" style="--x:${r.x}%;--y:${r.y}%" data-region="${i}" aria-pressed="${i===0}"><span class="node-dot"></span><span>${r.name}</span></button>`).join('')}</div><p class="network-caption">Schematic network · Not a geographic boundary map</p><div class="region-detail" aria-live="polite"><p class="eyebrow" id="region-label">${regions[0].label}</p><h3 id="region-name">${regions[0].name}</h3><p id="region-description">${regions[0].detail}</p></div></div><div class="location-list">${regions.map((r,i)=>`<button data-region="${i}" class="location-row ${i===0?'selected':''}" aria-pressed="${i===0}"><span><strong>${r.name}</strong><small>${r.label}</small></span><span aria-hidden="true">↗</span></button>`).join('')}<p class="location-note">Project offices and works locations are listed on company letterhead. Himachal Pradesh is strategic regional coverage.</p></div></div></section>
 <section class="recognition section" id="recognition"><div class="recognition-copy">${heading('07 / INDUSTRY RECOGNITION','Recognition beyond<br><span>the project site.</span>')}<p>Our work and industry participation reflect a commitment to engineering standards, professional execution and long-term institutional relationships.</p><span class="photo-caption">HANS BUILDERS<br>Industry recognition & professional engagement</span></div><figure class="reveal"><img src="./assets/recognition.webp" width="1280" height="853" loading="lazy" alt="Formal industry recognition and professional engagement photograph supplied by Hans Builders"><figcaption>Industry recognition & professional engagement</figcaption></figure></section>
 <section class="organisation section" id="organisation"><div class="organisation-title">${heading('08 / OUR ORGANISATION','One organisation.<br><span>One engineering standard.</span>')}<p>A multidisciplinary organisation aligned around engineering discipline, execution standards and project accountability.</p></div><figure class="reveal"><img src="./assets/organisation.webp" width="800" height="600" loading="lazy" alt="Hans Builders supplied corporate group photograph"><figcaption>People. Purpose. Shared standards.</figcaption></figure></section>
 <section class="closing-statement"><p class="eyebrow light">PEOPLE / PROJECTS / PROGRESS</p><h2><span class="reveal">Building the future</span><span class="reveal">of North India.</span><em class="reveal">Engineered for trust.</em></h2><p>From civil infrastructure to highway construction, an established corporate foundation for what comes next.</p><a class="button gold" href="#contact">Let’s start a conversation <span aria-hidden="true">↗</span></a></section>
 <section class="section contact" id="contact"><div class="contact-copy">${heading('09 / START A CONVERSATION','Let’s build something <em>enduring.</em>')}<p>Discuss civil construction, infrastructure development, engineering or project partnership opportunities with Hans Builders.</p><div class="contact-details"><a href="tel:+918847672490"><small>CALL US</small>+91 88476 72490 <span aria-hidden="true">↗</span></a><a href="mailto:enquiry@hansbuilders.com"><small>EMAIL US</small>enquiry@hansbuilders.com <span aria-hidden="true">↗</span></a><div><small>REGISTERED OFFICE</small><address>IE/2, Jhandewalan Extension<br>New Delhi, Delhi 110055, India</address></div></div></div></section>
 <footer class="site-footer"><div class="footer-main"><div><a class="brand" href="#home"><img src="./assets/logo.webp" width="64" height="46" alt="HB"><span>HANS BUILDERS<small>CONTRACTORS & ENGINEERS</small></span></a><p>Hans Builders Contractors<br>and Engineer Pvt. Ltd.</p><span class="footer-tagline">BUILDING WITH PURPOSE, SINCE 1978.</span></div><nav aria-label="Footer navigation"><a href="#company">Company</a><a href="#capabilities">Capabilities</a><a href="#project-showcase">Project capabilities</a><a href="#compliance">Compliance</a><a href="#footprint">Footprint</a><a href="#contact">Contact</a></nav><div class="footer-contact"><p>IE/2, Jhandewalan Extension<br>New Delhi, Delhi 110055, India</p><a href="mailto:enquiry@hansbuilders.com">enquiry@hansbuilders.com</a><a href="tel:+918847672490">+91 88476 72490</a><a href="https://www.hansbuilders.com/">www.hansbuilders.com</a></div></div><div class="footer-sectors">Government Contractor <span>·</span> Civil Construction <span>·</span> Infrastructure Development <span>·</span> Engineering <span>·</span> Highway Construction</div><div class="footer-bottom"><p>© 2018 Hans Builders Contractors and Engineer Pvt. Ltd. All Rights Reserved.</p><a href="#home">Back to top ↑</a></div></footer>`;
}
